package yamp.com.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import yamp.com.model.BraAgnTyp;
import yamp.com.model.BraAgnTypExample;

public interface BraAgnTypMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    long countByExample(BraAgnTypExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int deleteByExample(BraAgnTypExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int insert(BraAgnTyp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int insertSelective(BraAgnTyp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    List<BraAgnTyp> selectByExample(BraAgnTypExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    BraAgnTyp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") BraAgnTyp record, @Param("example") BraAgnTypExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int updateByExample(@Param("record") BraAgnTyp record, @Param("example") BraAgnTypExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int updateByPrimaryKeySelective(BraAgnTyp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bra_agn_typ
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    int updateByPrimaryKey(BraAgnTyp record);
}