package yamp.com.model;

import java.util.ArrayList;
import java.util.List;

public class BillExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public BillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNull() {
            addCriterion("order_code is null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNotNull() {
            addCriterion("order_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeEqualTo(String value) {
            addCriterion("order_code =", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotEqualTo(String value) {
            addCriterion("order_code <>", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThan(String value) {
            addCriterion("order_code >", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("order_code >=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThan(String value) {
            addCriterion("order_code <", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("order_code <=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLike(String value) {
            addCriterion("order_code like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotLike(String value) {
            addCriterion("order_code not like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIn(List<String> values) {
            addCriterion("order_code in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotIn(List<String> values) {
            addCriterion("order_code not in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeBetween(String value1, String value2) {
            addCriterion("order_code between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotBetween(String value1, String value2) {
            addCriterion("order_code not between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andTransactionIsNull() {
            addCriterion("transaction is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIsNotNull() {
            addCriterion("transaction is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionEqualTo(Double value) {
            addCriterion("transaction =", value, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionNotEqualTo(Double value) {
            addCriterion("transaction <>", value, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionGreaterThan(Double value) {
            addCriterion("transaction >", value, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionGreaterThanOrEqualTo(Double value) {
            addCriterion("transaction >=", value, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionLessThan(Double value) {
            addCriterion("transaction <", value, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionLessThanOrEqualTo(Double value) {
            addCriterion("transaction <=", value, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionIn(List<Double> values) {
            addCriterion("transaction in", values, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionNotIn(List<Double> values) {
            addCriterion("transaction not in", values, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionBetween(Double value1, Double value2) {
            addCriterion("transaction between", value1, value2, "transaction");
            return (Criteria) this;
        }

        public Criteria andTransactionNotBetween(Double value1, Double value2) {
            addCriterion("transaction not between", value1, value2, "transaction");
            return (Criteria) this;
        }

        public Criteria andPlayerIsNull() {
            addCriterion("player is null");
            return (Criteria) this;
        }

        public Criteria andPlayerIsNotNull() {
            addCriterion("player is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerEqualTo(String value) {
            addCriterion("player =", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerNotEqualTo(String value) {
            addCriterion("player <>", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerGreaterThan(String value) {
            addCriterion("player >", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerGreaterThanOrEqualTo(String value) {
            addCriterion("player >=", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerLessThan(String value) {
            addCriterion("player <", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerLessThanOrEqualTo(String value) {
            addCriterion("player <=", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerLike(String value) {
            addCriterion("player like", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerNotLike(String value) {
            addCriterion("player not like", value, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerIn(List<String> values) {
            addCriterion("player in", values, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerNotIn(List<String> values) {
            addCriterion("player not in", values, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerBetween(String value1, String value2) {
            addCriterion("player between", value1, value2, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerNotBetween(String value1, String value2) {
            addCriterion("player not between", value1, value2, "player");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeIsNull() {
            addCriterion("player_time is null");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeIsNotNull() {
            addCriterion("player_time is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeEqualTo(String value) {
            addCriterion("player_time =", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeNotEqualTo(String value) {
            addCriterion("player_time <>", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeGreaterThan(String value) {
            addCriterion("player_time >", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeGreaterThanOrEqualTo(String value) {
            addCriterion("player_time >=", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeLessThan(String value) {
            addCriterion("player_time <", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeLessThanOrEqualTo(String value) {
            addCriterion("player_time <=", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeLike(String value) {
            addCriterion("player_time like", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeNotLike(String value) {
            addCriterion("player_time not like", value, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeIn(List<String> values) {
            addCriterion("player_time in", values, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeNotIn(List<String> values) {
            addCriterion("player_time not in", values, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeBetween(String value1, String value2) {
            addCriterion("player_time between", value1, value2, "playerTime");
            return (Criteria) this;
        }

        public Criteria andPlayerTimeNotBetween(String value1, String value2) {
            addCriterion("player_time not between", value1, value2, "playerTime");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsIsNull() {
            addCriterion("goods_ids is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsIsNotNull() {
            addCriterion("goods_ids is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsEqualTo(String value) {
            addCriterion("goods_ids =", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsNotEqualTo(String value) {
            addCriterion("goods_ids <>", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsGreaterThan(String value) {
            addCriterion("goods_ids >", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsGreaterThanOrEqualTo(String value) {
            addCriterion("goods_ids >=", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsLessThan(String value) {
            addCriterion("goods_ids <", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsLessThanOrEqualTo(String value) {
            addCriterion("goods_ids <=", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsLike(String value) {
            addCriterion("goods_ids like", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsNotLike(String value) {
            addCriterion("goods_ids not like", value, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsIn(List<String> values) {
            addCriterion("goods_ids in", values, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsNotIn(List<String> values) {
            addCriterion("goods_ids not in", values, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsBetween(String value1, String value2) {
            addCriterion("goods_ids between", value1, value2, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andGoodsIdsNotBetween(String value1, String value2) {
            addCriterion("goods_ids not between", value1, value2, "goodsIds");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusIsNull() {
            addCriterion("line_order_status is null");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusIsNotNull() {
            addCriterion("line_order_status is not null");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusEqualTo(Integer value) {
            addCriterion("line_order_status =", value, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusNotEqualTo(Integer value) {
            addCriterion("line_order_status <>", value, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusGreaterThan(Integer value) {
            addCriterion("line_order_status >", value, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("line_order_status >=", value, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusLessThan(Integer value) {
            addCriterion("line_order_status <", value, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusLessThanOrEqualTo(Integer value) {
            addCriterion("line_order_status <=", value, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusIn(List<Integer> values) {
            addCriterion("line_order_status in", values, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusNotIn(List<Integer> values) {
            addCriterion("line_order_status not in", values, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusBetween(Integer value1, Integer value2) {
            addCriterion("line_order_status between", value1, value2, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andLineOrderStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("line_order_status not between", value1, value2, "lineOrderStatus");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusIsNull() {
            addCriterion("into_or_out_status is null");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusIsNotNull() {
            addCriterion("into_or_out_status is not null");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusEqualTo(Integer value) {
            addCriterion("into_or_out_status =", value, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusNotEqualTo(Integer value) {
            addCriterion("into_or_out_status <>", value, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusGreaterThan(Integer value) {
            addCriterion("into_or_out_status >", value, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("into_or_out_status >=", value, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusLessThan(Integer value) {
            addCriterion("into_or_out_status <", value, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusLessThanOrEqualTo(Integer value) {
            addCriterion("into_or_out_status <=", value, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusIn(List<Integer> values) {
            addCriterion("into_or_out_status in", values, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusNotIn(List<Integer> values) {
            addCriterion("into_or_out_status not in", values, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusBetween(Integer value1, Integer value2) {
            addCriterion("into_or_out_status between", value1, value2, "intoOrOutStatus");
            return (Criteria) this;
        }

        public Criteria andIntoOrOutStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("into_or_out_status not between", value1, value2, "intoOrOutStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 27 08:40:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbg.generated Wed Jun 27 08:40:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}