package yamp.com.model;

public class BraAgnTyp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.id
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.name
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.status
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.pid
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.creater
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.create_time
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.updater
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bra_agn_typ.update_time
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.id
     *
     * @return the value of bra_agn_typ.id
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.id
     *
     * @param id the value for bra_agn_typ.id
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.name
     *
     * @return the value of bra_agn_typ.name
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.name
     *
     * @param name the value for bra_agn_typ.name
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.status
     *
     * @return the value of bra_agn_typ.status
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.status
     *
     * @param status the value for bra_agn_typ.status
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.pid
     *
     * @return the value of bra_agn_typ.pid
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.pid
     *
     * @param pid the value for bra_agn_typ.pid
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.creater
     *
     * @return the value of bra_agn_typ.creater
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.creater
     *
     * @param creater the value for bra_agn_typ.creater
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.create_time
     *
     * @return the value of bra_agn_typ.create_time
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.create_time
     *
     * @param createTime the value for bra_agn_typ.create_time
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.updater
     *
     * @return the value of bra_agn_typ.updater
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.updater
     *
     * @param updater the value for bra_agn_typ.updater
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bra_agn_typ.update_time
     *
     * @return the value of bra_agn_typ.update_time
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bra_agn_typ.update_time
     *
     * @param updateTime the value for bra_agn_typ.update_time
     *
     * @mbg.generated Wed Jun 20 15:49:05 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}