package yamp.com.model;

import java.util.ArrayList;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(Integer value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(Integer value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(Integer value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(Integer value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<Integer> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<Integer> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBranchPriceIsNull() {
            addCriterion("branch_price is null");
            return (Criteria) this;
        }

        public Criteria andBranchPriceIsNotNull() {
            addCriterion("branch_price is not null");
            return (Criteria) this;
        }

        public Criteria andBranchPriceEqualTo(Double value) {
            addCriterion("branch_price =", value, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceNotEqualTo(Double value) {
            addCriterion("branch_price <>", value, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceGreaterThan(Double value) {
            addCriterion("branch_price >", value, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("branch_price >=", value, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceLessThan(Double value) {
            addCriterion("branch_price <", value, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceLessThanOrEqualTo(Double value) {
            addCriterion("branch_price <=", value, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceIn(List<Double> values) {
            addCriterion("branch_price in", values, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceNotIn(List<Double> values) {
            addCriterion("branch_price not in", values, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceBetween(Double value1, Double value2) {
            addCriterion("branch_price between", value1, value2, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBranchPriceNotBetween(Double value1, Double value2) {
            addCriterion("branch_price not between", value1, value2, "branchPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceIsNull() {
            addCriterion("box_price is null");
            return (Criteria) this;
        }

        public Criteria andBoxPriceIsNotNull() {
            addCriterion("box_price is not null");
            return (Criteria) this;
        }

        public Criteria andBoxPriceEqualTo(Double value) {
            addCriterion("box_price =", value, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceNotEqualTo(Double value) {
            addCriterion("box_price <>", value, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceGreaterThan(Double value) {
            addCriterion("box_price >", value, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("box_price >=", value, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceLessThan(Double value) {
            addCriterion("box_price <", value, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceLessThanOrEqualTo(Double value) {
            addCriterion("box_price <=", value, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceIn(List<Double> values) {
            addCriterion("box_price in", values, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceNotIn(List<Double> values) {
            addCriterion("box_price not in", values, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceBetween(Double value1, Double value2) {
            addCriterion("box_price between", value1, value2, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBoxPriceNotBetween(Double value1, Double value2) {
            addCriterion("box_price not between", value1, value2, "boxPrice");
            return (Criteria) this;
        }

        public Criteria andBranchCountIsNull() {
            addCriterion("branch_count is null");
            return (Criteria) this;
        }

        public Criteria andBranchCountIsNotNull() {
            addCriterion("branch_count is not null");
            return (Criteria) this;
        }

        public Criteria andBranchCountEqualTo(Integer value) {
            addCriterion("branch_count =", value, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountNotEqualTo(Integer value) {
            addCriterion("branch_count <>", value, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountGreaterThan(Integer value) {
            addCriterion("branch_count >", value, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("branch_count >=", value, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountLessThan(Integer value) {
            addCriterion("branch_count <", value, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountLessThanOrEqualTo(Integer value) {
            addCriterion("branch_count <=", value, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountIn(List<Integer> values) {
            addCriterion("branch_count in", values, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountNotIn(List<Integer> values) {
            addCriterion("branch_count not in", values, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountBetween(Integer value1, Integer value2) {
            addCriterion("branch_count between", value1, value2, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBranchCountNotBetween(Integer value1, Integer value2) {
            addCriterion("branch_count not between", value1, value2, "branchCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountIsNull() {
            addCriterion("box_count is null");
            return (Criteria) this;
        }

        public Criteria andBoxCountIsNotNull() {
            addCriterion("box_count is not null");
            return (Criteria) this;
        }

        public Criteria andBoxCountEqualTo(Integer value) {
            addCriterion("box_count =", value, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountNotEqualTo(Integer value) {
            addCriterion("box_count <>", value, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountGreaterThan(Integer value) {
            addCriterion("box_count >", value, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("box_count >=", value, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountLessThan(Integer value) {
            addCriterion("box_count <", value, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountLessThanOrEqualTo(Integer value) {
            addCriterion("box_count <=", value, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountIn(List<Integer> values) {
            addCriterion("box_count in", values, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountNotIn(List<Integer> values) {
            addCriterion("box_count not in", values, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountBetween(Integer value1, Integer value2) {
            addCriterion("box_count between", value1, value2, "boxCount");
            return (Criteria) this;
        }

        public Criteria andBoxCountNotBetween(Integer value1, Integer value2) {
            addCriterion("box_count not between", value1, value2, "boxCount");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumIsNull() {
            addCriterion("each_box_num is null");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumIsNotNull() {
            addCriterion("each_box_num is not null");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumEqualTo(Integer value) {
            addCriterion("each_box_num =", value, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumNotEqualTo(Integer value) {
            addCriterion("each_box_num <>", value, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumGreaterThan(Integer value) {
            addCriterion("each_box_num >", value, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("each_box_num >=", value, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumLessThan(Integer value) {
            addCriterion("each_box_num <", value, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumLessThanOrEqualTo(Integer value) {
            addCriterion("each_box_num <=", value, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumIn(List<Integer> values) {
            addCriterion("each_box_num in", values, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumNotIn(List<Integer> values) {
            addCriterion("each_box_num not in", values, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumBetween(Integer value1, Integer value2) {
            addCriterion("each_box_num between", value1, value2, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andEachBoxNumNotBetween(Integer value1, Integer value2) {
            addCriterion("each_box_num not between", value1, value2, "eachBoxNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTypeTitleIsNull() {
            addCriterion("type_title is null");
            return (Criteria) this;
        }

        public Criteria andTypeTitleIsNotNull() {
            addCriterion("type_title is not null");
            return (Criteria) this;
        }

        public Criteria andTypeTitleEqualTo(String value) {
            addCriterion("type_title =", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotEqualTo(String value) {
            addCriterion("type_title <>", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleGreaterThan(String value) {
            addCriterion("type_title >", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleGreaterThanOrEqualTo(String value) {
            addCriterion("type_title >=", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleLessThan(String value) {
            addCriterion("type_title <", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleLessThanOrEqualTo(String value) {
            addCriterion("type_title <=", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleLike(String value) {
            addCriterion("type_title like", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotLike(String value) {
            addCriterion("type_title not like", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleIn(List<String> values) {
            addCriterion("type_title in", values, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotIn(List<String> values) {
            addCriterion("type_title not in", values, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleBetween(String value1, String value2) {
            addCriterion("type_title between", value1, value2, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotBetween(String value1, String value2) {
            addCriterion("type_title not between", value1, value2, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceIsNull() {
            addCriterion("branch_bid_price is null");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceIsNotNull() {
            addCriterion("branch_bid_price is not null");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceEqualTo(Double value) {
            addCriterion("branch_bid_price =", value, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceNotEqualTo(Double value) {
            addCriterion("branch_bid_price <>", value, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceGreaterThan(Double value) {
            addCriterion("branch_bid_price >", value, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("branch_bid_price >=", value, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceLessThan(Double value) {
            addCriterion("branch_bid_price <", value, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceLessThanOrEqualTo(Double value) {
            addCriterion("branch_bid_price <=", value, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceIn(List<Double> values) {
            addCriterion("branch_bid_price in", values, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceNotIn(List<Double> values) {
            addCriterion("branch_bid_price not in", values, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceBetween(Double value1, Double value2) {
            addCriterion("branch_bid_price between", value1, value2, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBranchBidPriceNotBetween(Double value1, Double value2) {
            addCriterion("branch_bid_price not between", value1, value2, "branchBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceIsNull() {
            addCriterion("box_bid_price is null");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceIsNotNull() {
            addCriterion("box_bid_price is not null");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceEqualTo(Double value) {
            addCriterion("box_bid_price =", value, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceNotEqualTo(Double value) {
            addCriterion("box_bid_price <>", value, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceGreaterThan(Double value) {
            addCriterion("box_bid_price >", value, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("box_bid_price >=", value, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceLessThan(Double value) {
            addCriterion("box_bid_price <", value, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceLessThanOrEqualTo(Double value) {
            addCriterion("box_bid_price <=", value, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceIn(List<Double> values) {
            addCriterion("box_bid_price in", values, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceNotIn(List<Double> values) {
            addCriterion("box_bid_price not in", values, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceBetween(Double value1, Double value2) {
            addCriterion("box_bid_price between", value1, value2, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andBoxBidPriceNotBetween(Double value1, Double value2) {
            addCriterion("box_bid_price not between", value1, value2, "boxBidPrice");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNull() {
            addCriterion("img_url is null");
            return (Criteria) this;
        }

        public Criteria andImgUrlIsNotNull() {
            addCriterion("img_url is not null");
            return (Criteria) this;
        }

        public Criteria andImgUrlEqualTo(String value) {
            addCriterion("img_url =", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotEqualTo(String value) {
            addCriterion("img_url <>", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThan(String value) {
            addCriterion("img_url >", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("img_url >=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThan(String value) {
            addCriterion("img_url <", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLessThanOrEqualTo(String value) {
            addCriterion("img_url <=", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlLike(String value) {
            addCriterion("img_url like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotLike(String value) {
            addCriterion("img_url not like", value, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlIn(List<String> values) {
            addCriterion("img_url in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotIn(List<String> values) {
            addCriterion("img_url not in", values, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlBetween(String value1, String value2) {
            addCriterion("img_url between", value1, value2, "imgUrl");
            return (Criteria) this;
        }

        public Criteria andImgUrlNotBetween(String value1, String value2) {
            addCriterion("img_url not between", value1, value2, "imgUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 20 16:18:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}