package yamp.com.model;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type_id
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.branch_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Double branchPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.box_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Double boxPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.branch_count
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Integer branchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.box_count
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Integer boxCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.each_box_num
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Integer eachBoxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.creater
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.updater
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.type_title
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String typeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.branch_bid_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Double branchBidPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.box_bid_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private Double boxBidPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img_url
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type_id
     *
     * @return the value of goods.type_id
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type_id
     *
     * @param typeId the value for goods.type_id
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.branch_price
     *
     * @return the value of goods.branch_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Double getBranchPrice() {
        return branchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.branch_price
     *
     * @param branchPrice the value for goods.branch_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setBranchPrice(Double branchPrice) {
        this.branchPrice = branchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.box_price
     *
     * @return the value of goods.box_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Double getBoxPrice() {
        return boxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.box_price
     *
     * @param boxPrice the value for goods.box_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setBoxPrice(Double boxPrice) {
        this.boxPrice = boxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.branch_count
     *
     * @return the value of goods.branch_count
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Integer getBranchCount() {
        return branchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.branch_count
     *
     * @param branchCount the value for goods.branch_count
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setBranchCount(Integer branchCount) {
        this.branchCount = branchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.box_count
     *
     * @return the value of goods.box_count
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Integer getBoxCount() {
        return boxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.box_count
     *
     * @param boxCount the value for goods.box_count
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setBoxCount(Integer boxCount) {
        this.boxCount = boxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.each_box_num
     *
     * @return the value of goods.each_box_num
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Integer getEachBoxNum() {
        return eachBoxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.each_box_num
     *
     * @param eachBoxNum the value for goods.each_box_num
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setEachBoxNum(Integer eachBoxNum) {
        this.eachBoxNum = eachBoxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.creater
     *
     * @return the value of goods.creater
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.creater
     *
     * @param creater the value for goods.creater
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.updater
     *
     * @return the value of goods.updater
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.updater
     *
     * @param updater the value for goods.updater
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.type_title
     *
     * @return the value of goods.type_title
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getTypeTitle() {
        return typeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.type_title
     *
     * @param typeTitle the value for goods.type_title
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setTypeTitle(String typeTitle) {
        this.typeTitle = typeTitle == null ? null : typeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.branch_bid_price
     *
     * @return the value of goods.branch_bid_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Double getBranchBidPrice() {
        return branchBidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.branch_bid_price
     *
     * @param branchBidPrice the value for goods.branch_bid_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setBranchBidPrice(Double branchBidPrice) {
        this.branchBidPrice = branchBidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.box_bid_price
     *
     * @return the value of goods.box_bid_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public Double getBoxBidPrice() {
        return boxBidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.box_bid_price
     *
     * @param boxBidPrice the value for goods.box_bid_price
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setBoxBidPrice(Double boxBidPrice) {
        this.boxBidPrice = boxBidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img_url
     *
     * @return the value of goods.img_url
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img_url
     *
     * @param imgUrl the value for goods.img_url
     *
     * @mbg.generated Wed Jun 20 16:18:10 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}