package yamp.com.model;

public class ShoppingCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.customer_id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.goods_id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.discount
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.box_total
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Integer boxTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.status
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.branch_total
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Integer branchTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.transaction
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    private Double transaction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.id
     *
     * @return the value of shopping_car.id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.id
     *
     * @param id the value for shopping_car.id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.customer_id
     *
     * @return the value of shopping_car.customer_id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.customer_id
     *
     * @param customerId the value for shopping_car.customer_id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.goods_id
     *
     * @return the value of shopping_car.goods_id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.goods_id
     *
     * @param goodsId the value for shopping_car.goods_id
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.discount
     *
     * @return the value of shopping_car.discount
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.discount
     *
     * @param discount the value for shopping_car.discount
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.box_total
     *
     * @return the value of shopping_car.box_total
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Integer getBoxTotal() {
        return boxTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.box_total
     *
     * @param boxTotal the value for shopping_car.box_total
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setBoxTotal(Integer boxTotal) {
        this.boxTotal = boxTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.status
     *
     * @return the value of shopping_car.status
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.status
     *
     * @param status the value for shopping_car.status
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.branch_total
     *
     * @return the value of shopping_car.branch_total
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Integer getBranchTotal() {
        return branchTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.branch_total
     *
     * @param branchTotal the value for shopping_car.branch_total
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setBranchTotal(Integer branchTotal) {
        this.branchTotal = branchTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.transaction
     *
     * @return the value of shopping_car.transaction
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public Double getTransaction() {
        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.transaction
     *
     * @param transaction the value for shopping_car.transaction
     *
     * @mbg.generated Wed Jun 20 16:18:41 CST 2018
     */
    public void setTransaction(Double transaction) {
        this.transaction = transaction;
    }
}