package yamp.com.model;

public class ShoppingCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.customer_id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.goods_id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.discount
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.goods_name
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.status
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.branch_total
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private Integer branchTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.transaction
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private Double transaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.goods_url
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private String goodsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_car.goods_branch_price
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    private Double goodsBranchPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.id
     *
     * @return the value of shopping_car.id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.id
     *
     * @param id the value for shopping_car.id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.customer_id
     *
     * @return the value of shopping_car.customer_id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.customer_id
     *
     * @param customerId the value for shopping_car.customer_id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.goods_id
     *
     * @return the value of shopping_car.goods_id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.goods_id
     *
     * @param goodsId the value for shopping_car.goods_id
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.discount
     *
     * @return the value of shopping_car.discount
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.discount
     *
     * @param discount the value for shopping_car.discount
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.goods_name
     *
     * @return the value of shopping_car.goods_name
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.goods_name
     *
     * @param goodsName the value for shopping_car.goods_name
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.status
     *
     * @return the value of shopping_car.status
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.status
     *
     * @param status the value for shopping_car.status
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.branch_total
     *
     * @return the value of shopping_car.branch_total
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public Integer getBranchTotal() {
        return branchTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.branch_total
     *
     * @param branchTotal the value for shopping_car.branch_total
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setBranchTotal(Integer branchTotal) {
        this.branchTotal = branchTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.transaction
     *
     * @return the value of shopping_car.transaction
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public Double getTransaction() {
        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.transaction
     *
     * @param transaction the value for shopping_car.transaction
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setTransaction(Double transaction) {
        this.transaction = transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.goods_url
     *
     * @return the value of shopping_car.goods_url
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.goods_url
     *
     * @param goodsUrl the value for shopping_car.goods_url
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl == null ? null : goodsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_car.goods_branch_price
     *
     * @return the value of shopping_car.goods_branch_price
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public Double getGoodsBranchPrice() {
        return goodsBranchPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_car.goods_branch_price
     *
     * @param goodsBranchPrice the value for shopping_car.goods_branch_price
     *
     * @mbg.generated Tue Jul 03 14:39:27 CST 2018
     */
    public void setGoodsBranchPrice(Double goodsBranchPrice) {
        this.goodsBranchPrice = goodsBranchPrice;
    }
}