package yamp.com.model;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.brand_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.agent_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.type_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.count
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.creater
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.create_time
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.updater
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.update_time
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.status
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.brand_name
     *
     * @return the value of stock.brand_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.brand_name
     *
     * @param brandName the value for stock.brand_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.agent_name
     *
     * @return the value of stock.agent_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.agent_name
     *
     * @param agentName the value for stock.agent_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.type_name
     *
     * @return the value of stock.type_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.type_name
     *
     * @param typeName the value for stock.type_name
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.count
     *
     * @return the value of stock.count
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.count
     *
     * @param count the value for stock.count
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.creater
     *
     * @return the value of stock.creater
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.creater
     *
     * @param creater the value for stock.creater
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.create_time
     *
     * @return the value of stock.create_time
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.create_time
     *
     * @param createTime the value for stock.create_time
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.updater
     *
     * @return the value of stock.updater
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.updater
     *
     * @param updater the value for stock.updater
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.update_time
     *
     * @return the value of stock.update_time
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.update_time
     *
     * @param updateTime the value for stock.update_time
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.status
     *
     * @return the value of stock.status
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.status
     *
     * @param status the value for stock.status
     *
     * @mbg.generated Wed Jun 20 15:46:14 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}